docs/AboutUs.md

Please have a look at my AboutUs changes

Update AboutUs for a PR test

---

docs/AboutUs.md

add hans name

---

src/main/java/seedu/planitarium/Income.java
src/main/java/seedu/planitarium/IncomeList.java

Standarized format of attributes with han's expenditure class.
Also removed any exception handling, discussed with si zheng who is doing the parser class.
Agree that parser/command will sanitise inputs before calling the class functions rather than relying on class itself.
Exceptions handling will be done in those 2 classes.

Added Income and IncomeList class

---

src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java

Synchronise Person and PersonList classes with rest of the code base

---

src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java

Add javadoc comments and methods to get number of incomes and expenditures a person has

---

src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java

Fix accessibility of Person and PersonList members

---

src/main/java/seedu/planitarium/parser/Parser.java

Parser fix synchronisation bugs

---

src/main/java/seedu/planitarium/parser/Parser.java

Parser add more parser methods

---

src/main/java/exceptions/InvalidIndexException.java
src/main/java/exceptions/InvalidMoneyException.java
src/main/java/exceptions/MissingDelimiterException.java
src/main/java/seedu/planitarium/parser/Parser.java

Update Parser class with getter methods and exceptions

---

src/main/java/seedu/planitarium/income/Income.java
src/main/java/seedu/planitarium/income/IncomeList.java
src/main/java/seedu/planitarium/person/Person.java

Shifted both classes into package

Updated Income and IncomeList class with methods.

---

src/main/java/seedu/planitarium/income/IncomeList.java
src/main/java/seedu/planitarium/person/Person.java

Minor bug fix to function type

---

src/test/java/seedu/planitarium/income/IncomeListTest.java
src/test/java/seedu/planitarium/income/IncomeTest.java

Fixes #60 
Fixes #59 
Implemented JUnit test skeleton for both classes.

JUnit testing skeleton for Income and IncomeList

---

src/main/java/seedu/planitarium/expenditure/Expenditure.java
src/main/java/seedu/planitarium/expenditure/ExpenditureList.java

Add assertion to expenditure

---

PersonList.log
PlanITarium.log
src/main/java/seedu/planitarium/PlanITarium.java
src/main/java/seedu/planitarium/ProjectLogger.java
src/main/java/seedu/planitarium/commands/RemainCommand.java
src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java
src/test/java/seedu/planitarium/person/PersonListTest.java
src/test/java/seedu/planitarium/person/PersonTest.java

Fix logger bugs and increase JUnit testing for PersonList and Person classes

---

src/main/java/seedu/planitarium/commands/AddPersonCommand.java
src/main/java/seedu/planitarium/exceptions/DuplicateDelimiterException.java
src/main/java/seedu/planitarium/parser/Parser.java

Add logging for Parser class and fix minor bug

---

src/main/java/seedu/planitarium/income/Income.java
src/main/java/seedu/planitarium/income/IncomeList.java

Added assert to Income and Incomelist

---

PlanITarium.log
src/main/java/seedu/planitarium/parser/Parser.java
src/test/java/seedu/planitarium/parser/ParserTest.java

Add more JUnit tests for Parser class

---

src/main/java/seedu/planitarium/money/Expenditure.java
src/main/java/seedu/planitarium/money/ExpenditureList.java
src/main/java/seedu/planitarium/money/Income.java
src/main/java/seedu/planitarium/money/IncomeList.java
src/main/java/seedu/planitarium/money/Money.java
src/main/java/seedu/planitarium/money/MoneyList.java
src/main/java/seedu/planitarium/person/Person.java
src/test/java/seedu/planitarium/expenditure/ExpenditureListTest.java
src/test/java/seedu/planitarium/expenditure/ExpenditureTest.java
src/test/java/seedu/planitarium/income/IncomeListTest.java

Created parent class of Income and Expenditure

Money superclass

---

docs/assets/css/style.scss
src/main/java/seedu/planitarium/commands/AddRecordCommand.java
src/main/java/seedu/planitarium/money/Expenditure.java
src/main/java/seedu/planitarium/money/ExpenditureList.java
src/main/java/seedu/planitarium/money/Income.java
src/main/java/seedu/planitarium/money/IncomeList.java
src/main/java/seedu/planitarium/money/Money.java
src/main/java/seedu/planitarium/money/MoneyList.java
src/main/java/seedu/planitarium/parser/Parser.java
src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java
src/main/java/seedu/planitarium/storage/Storage.java
src/test/java/seedu/planitarium/expenditure/ExpenditureListTest.java
src/test/java/seedu/planitarium/expenditure/ExpenditureTest.java
src/test/java/seedu/planitarium/income/IncomeListTest.java
src/test/java/seedu/planitarium/income/IncomeTest.java
src/test/java/seedu/planitarium/parser/ParserTest.java
src/test/java/seedu/planitarium/person/PersonTest.java

Fixes #100 
Fixes #132
Mainly concerned with adding of new attributes, isPermanent and initDate.
Also fixed logging file creation bug by making the logger for person and money class static.

Added new functionalities to Money and MoneyList class

---

src/main/java/seedu/planitarium/storage/Storage.java
src/test/java/seedu/planitarium/storage/StorageTest.java

Added Javadocs to Storage class

---

docs/assets/css/style.scss
src/main/java/seedu/planitarium/category/Category.java
src/main/java/seedu/planitarium/global/Constants.java
src/main/java/seedu/planitarium/parser/Parser.java
src/main/java/seedu/planitarium/parser/ParserUtility.java
src/test/java/seedu/planitarium/category/CategoryTest.java
src/test/java/seedu/planitarium/parser/ParserTest.java
src/test/java/seedu/planitarium/parser/ParserUtilityTest.java

Update Parser methods to match upcoming changes and refactor constants

---

src/main/java/seedu/planitarium/global/Constants.java
src/main/java/seedu/planitarium/person/Family.java
src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java
src/test/java/seedu/planitarium/person/FamilyTest.java
src/test/java/seedu/planitarium/person/PersonListTest.java
src/test/java/seedu/planitarium/person/PersonTest.java

Add support for category adding and save / loading

---

src/main/java/seedu/planitarium/exceptions/EmptyStringException.java
src/main/java/seedu/planitarium/exceptions/InvalidIndexException.java
src/main/java/seedu/planitarium/exceptions/InvalidMoneyException.java
src/test/java/seedu/planitarium/category/CategoryTest.java
src/test/java/seedu/planitarium/parser/ParserTest.java
src/test/java/seedu/planitarium/parser/ParserUtilityTest.java

Fix gradle tests for new exception extension and refactor constants

---

src/main/java/seedu/planitarium/storage/Storage.java

Added logger and bug fixes to Storage

---

src/main/java/seedu/planitarium/global/Constants.java
src/main/java/seedu/planitarium/person/Family.java
src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java
text-ui-test/input.txt

Clean up Family component and add new features

---

src/main/java/seedu/planitarium/person/Family.java
src/main/java/seedu/planitarium/person/Person.java
src/main/java/seedu/planitarium/person/PersonList.java
src/test/java/seedu/planitarium/person/FamilyTest.java
src/test/java/seedu/planitarium/person/PersonListTest.java
src/test/java/seedu/planitarium/person/PersonTest.java

Increase JUnit testing for Family component

---

src/main/java/seedu/planitarium/commands/DeletePersonCommand.java
src/main/java/seedu/planitarium/commands/EditRecordCommand.java
src/test/java/seedu/planitarium/money/ExpenditureTest.java
src/test/java/seedu/planitarium/money/IncomeTest.java

Fixes #186
Fixes #187 
Fixes #188 
Fixes #189 
Fixes #190 
Fixes #192 
Fixes #195 
Fixes #211 
Also fixed JUnit test for Gradle compliance.

V2.1 update

---

docs/UserGuide.md
src/main/java/seedu/planitarium/family/Family.java
src/test/java/seedu/planitarium/family/FamilyTest.java

Fixes #184 
Fixes #201 
Fixes #202 
Fixes #204 
Fixes #208

Cosmetic changes to overview and UG

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/team/jiarong.md
docs/team/tjiarong.md
src/main/java/seedu/planitarium/money/Money.java

Fixes #203 
Minor bug fix as well

Update PPP Draft

---

src/main/java/seedu/planitarium/family/Person.java
src/main/java/seedu/planitarium/money/Expenditure.java
src/main/java/seedu/planitarium/money/Income.java
src/main/java/seedu/planitarium/storage/Storage.java
src/test/java/seedu/planitarium/family/PersonTest.java
src/test/java/seedu/planitarium/money/ExpenditureTest.java
src/test/java/seedu/planitarium/money/IncomeTest.java

Split retrieving and setting of data for each person
small fix to saveName and saveString

added try catch for corrupted data

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/hanshenggit.md
docs/team/hlwang56.md
docs/team/teanweijun.md
text-ui-test/input.txt

Update v2.1 meeting changes
